### PR TITLE
Fix the ejs template and instruct the user what to do with the theme …

### LINKED ISSUE #19: Instruct the user what to do with their new theme file
**Enhancement**

Tom had a good idea:

the output should include a message along the lines of `please import 'src/themes/myTheme/theme' into your project to use your new theme`

### PR DESCRIPTION
**Pull request by umaar**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [ ] Unit or Functional tests are included in the PR

**Description:**

Fix the formatting of the generates theme file & instruct the user what to do with their new theme file

Resolves #19 and #7

### CODE REVIEW

File: src/createThemeFile.ts [hunk 1]
```diff
@@ -49,6 +49,8 @@ function createThemeFile({
 			CSSModules: CSSModulesData
 		}
 	);
+
+	console.log(`Please import '${fullThemeFilePath}' into your project to use your new theme`);
```
Comment (tomdye) [inline src/createThemeFile.ts]: perhaps add `chalk.bold` around `fullThemeFilePath`

**Comment by umaar** [comment]
Example templates:

image

and 

image

File: src/createThemeFile.ts (hunk 1 above)
Comment (umaar) [reply src/createThemeFile.ts]: Ok done:

image
