### PR TITLE
Fix paths in generated theme file for windows

### LINKED ISSUE #35: Generated theme does not work in Windows
**Bug**

The generated theme file does not work in Windows. The `theme.ts` file that gets generated looks like,

```typescript
import * as accordionPane from './@dojo\widgets\accordion-pane/accordion-pane.m.css';

export default {
	'@dojo\widgets\accordion-pane': accordionPane
};
```

Notice specifically the path of the import, `./@dojo\widgets\accordion-pane/accordion-pane.m.css`. Those `\` characters are causing the import to fail and should be `/`.

To reproduce, simply use `dojo create theme --name test` in Windows...

### PR DESCRIPTION
**Pull request by KaneFreeman**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**
The join function in path detects the platform and if it is windows, it changes to using backslash `\` instead of forward slash `/`. Typescript expects forward slashes `/` regardless of platform. To correct this, the themeKey needs to be switched to forward slash `/` prior to use in the template.

The `errors if the package cannot be found` unit test needed to be modified to run properly on windows. The error message produced had backslashes '\' in the path, but the unit test expected the path to always have forward slashes `/`. Using the join function here instead of a static string resolves this issue, allowing the unit test to succeed on windows and mac/linux.

Resolves #35

### CODE REVIEW

File: src/createThemeFile.ts [hunk 1]
```diff
@@ -19,8 +18,8 @@ function createThemeFile({
 	renderFiles: any;
 }): void {
 	const mainThemeFileName = `theme.ts`;
-	const relativeThemeFilePath = join(themesDirectory, mainThemeFileName);
-	const absoluteThemeFilePath = join(process.cwd(), relativeThemeFilePath);
+	const relativeThemeFilePath = [themesDirectory, mainThemeFileName].join('/');
```
Comment (agubler) [inline src/createThemeFile.ts]: nit: template literals are probably nicer here `${themesDirectory}/${mainThemeFileName}`

Comment (KaneFreeman) [reply src/createThemeFile.ts]: Yeah, I didn't end up needing to touch this line, so I reverted it. Had missed some issues with the unit tests that led me to take a different path.

File: src/createThemeFile.ts [hunk 2]
```diff
@@ -30,6 +30,7 @@ function createThemeFile({
 	}
 
 	const CSSModulesData = themedWidgets.map(({ themeKey, fileName }) => {
+		themeKey = themeKey.split(/[\\]+/).join('/');
```
Comment (agubler) [inline src/createThemeFile.ts]: This is fine, we have used [slash from npm](https://www.npmjs.com/package/slash) before in other packages.
